# Generated by Django 4.2 on 2023-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContactForm',
            new_name='UsersMessages',
        ),
    ]
